services:
  - type: web
    name: mini-hackathon-laravel
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: ""
    plan: free
    region: oregon
    branch: main
    rootDir: .