.render.yamlservices:
  - type: web
    name: mini-hackathon-laravel
    env: php
    plan: free
    region: oregon
    branch: main
    rootDir: .
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
      php artisan db:seed --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
